class login:
    login_xpath = '//*[@id="links"]/div[1]/div[1]/nav/div/div[2]/div[2]/div[2]/button/span'
    username_xpath = '//*[@id="links"]/div[1]/div[2]/div/div[1]/div[1]/div/div[1]/div/div[1]/form/div[1]/div/input'
    password_xpath = '//*[@id="links"]/div[1]/div[2]/div/div[1]/div[1]/div/div[1]/div/div[1]/form/div[2]/div/input'
    # verification_xpath = ''
    login_in_xpath = '//*[@id="links"]/div[1]/div[2]/div/div[1]/div[1]/div/div[1]/div/div[1]/div[3]/div[1]/button/span'
    login_user_xpath = '//*[@id="app"]/div/div[1]/div[1]/div[1]/nav/div[2]/div[2]/div[2]/a'
    login_out_xpath = '//*[@id="app"]/div/div[1]/div[1]/div[1]/nav/div[2]/div[2]/div[2]/div/a[2]'
    login_zy_xpath = '//*[@id="app"]/div/div[1]/div[1]/div[1]/nav/div[2]/div[1]/a[1]'
    login_error_xpath = ''
    username_empty_xpath = ''
    password_empty_xpath = ''
    # verification_error_xpath = ''
    # verification_empty_xpath = ''
